### ISSUE TITLE
Why Token Not Working??

### ISSUE THREAD

**Issue by Phoenix1112** [gwen001/github-subdomains#7]
hello. thanks for this project... I used to use this program before but after installing the new version it doesn't work. my problem is entirely related to the github token. I'm creating a token at https://github.com/settings/tokens. but it says that the token was not found even though I used the token with the -t parameter.

![image](https://user-images.githubusercontent.com/42475284/113440424-0a0fa480-93f5-11eb-99f4-8214df3a9711.png)

(in the picture I have hidden half of the token)

Why is this happening?

**Comment by Phoenix1112** [comment]
There is an underscore in the new token I created on github. looks in the picture. There is no underscore when I review the old token. I think the program is sensitive to underlines. When I tried with the old token, I didn't get an error. but since I deleted the old token from my github page, no subdomain was found.

![image](https://user-images.githubusercontent.com/42475284/113442599-ffefa500-93f8-11eb-9e68-8ed09213121f.png)

**Comment by Shahad7278** [comment]
I have the same problem 
anyone has solved it?

**Comment by Sudan101** [comment]
Hi and thanks for the tool , I am facing the same issue (token not found)

**Comment by six2dez** [comment]
Fix PR poposed
https://github.com/gwen001/github-subdomains/pull/8/commits/4147360c4bf40d9184329333a34689f4adef1c7a

**Comment by Phoenix1112** [comment]
@six2dez thanks bro... it is worked for me...

**Comment by m3hrajbhat** [comment]
Instead of using prebuild binary, build new one which is main.go by typing `go build main.go` in the directory.This should build new binary then copy it to /bin and you are good to go.

**Comment by gwen001** [comment]
Should be fixed now. Sorry for being late...

**Comment by jayraj0x01** [comment]
i guess its not fixed ...

i am still facing the issue help....!

**Comment by jayraj0x01** [comment]
![error](https://github.com/gwen001/github-subdomains/assets/146564694/bc451fc0-6b30-4042-bf5d-a654dce4bfc8)

**Comment by gwen001** [comment]
See #26.
